name: test and publish
on:
  push:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: checks
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: go-semantic-release/action@v1.21.0
        with:
          hooks: goreleaser
          allow-initial-development-versions: true
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          MAINTAINER: ${{ vars.MAINTAINER }}
          MAIL: ${{ vars.MAIL }}